# Generated by Django 5.1.6 on 2025-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('alcohol', models.CharField(max_length=50, verbose_name='Алкоголь')),
                ('custom_alcohol', models.CharField(blank=True, max_length=100, verbose_name='Свой вариант алкоголя')),
                ('hot', models.CharField(max_length=50, verbose_name='Горячее')),
                ('music', models.TextField(verbose_name='Музыка')),
                ('car', models.BooleanField(default=False, verbose_name='На машине')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
        ),
    ]
